{% set name = "sagemaker-pytorch-container" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0b0ab9e7025d8afd8a144a42135fbf90a021ce71f9f014956b4d5a373656b28e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=2.7,<3.7
  run:
    - python >=2.7,<3.7
    - numpy >=1.16.4
    - pillow >=6.2.0
    - retrying >=1.3.3
    - sagemaker_containers
    - six >=1.12.0
    - pytorch-cpu
test:
  imports:
    - sagemaker_pytorch_container

about:
  home: https://github.com/aws/sagemaker-pytorch-container/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Docker container for running PyTorch scripts to train and host PyTorch models on SageMaker.
  doc_url: https://sagemaker.readthedocs.io/en/stable/using_pytorch.html
  dev_url: https://github.com/aws/sagemaker-pytorch-container/

extra:
  recipe-maintainers:
    - rluria14
    - benhuff
    - oblute
